spring:
  profiles:
    include:
      - secret

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB # 한개 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 100MB # 한개 요청의 최대 사이즈 (default: 10MB)

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${db.hostname}:${db.port}/${db.schema-name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto:  update  #update

    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 61613
    virtual-host: /

  mail:
    username: ${mail.username}
    host: smtp.gmail.com
    port: 587
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

#S3
cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
      stack.auto: false
      region.static: ap-northeast-2
      credentials:
        accessKey: ${s3.accessKey}
        secretKey: ${s3.secretKey}

