spring:
  profiles:
    include:
      - secret

  servlet:
    multipart:
      enabled: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${db.hostname}:${db.port}/${db.schema-name}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db.username}
    password: ${db.password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto:  update  #update

    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 61613
    virtual-host: /

  mail:
    username: ${mail.username}
    host: smtp.gmail.com
    port: 587
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          timeout: 50000
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379


